spring.application.name=hotelbooking
spring.datasource.url=jdbc:mysql://localhost:3306/projectdb
spring.datasource.username=appuser
spring.datasource.password=app123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=9090
razorpay.key.id=rzp_test_SKfh1FJYF4os6h
razorpay.key.secret=FMJOC68bZVLbqzW31iANzAGI
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aijthmathar@gmail.com
spring.mail.password=arvv nzkb urkr unpj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

